package enums;

public enum TestTableEnums {
    TEST_TABLE_ID_INDEX(1),
    INSERT_COLUMN_INDEX(2),
    UPDATE_COLUMN_INDEX(11),
    BROWSER_NAME_COLUMN_INDEX(9),
    ENV_COLUMN_INDEX(8),
    METHOD_NAME_COLUMN_INDEX(3),
    NAME_COLUMN_INDEX(1),
    SESSION_COLUMN_INDEX(5),
    ID_COLUMN_INDEX(0),
    AUTHOR_PARAMETER_INDEX(1),
    BROWSER_PARAMETER_INDEX(2),
    END_TIME_PARAMETER_INDEX(3),
    ENV_PARAMETER_INDEX(4),
    METHOD_NAME_PARAMETER_INDEX(5),
    NAME_PARAMETER_INDEX(6),
    PROJECT_ID_PARAMETER_INDEX(7),
    SESSION_ID_PARAMETER_INDEX(8),
    START_TIME_PARAMETER_INDEX(9),
    STATUS_ID_PARAMETER_INDEX(10),
    ID_PARAMETER_INDEX(11);

    public final Integer index;

    TestTableEnums(Integer index) {
        this.index = index;
    }
}
